const {EmbedBuilder} = require("discord.js");
const Logger = require("../../utils/Logger");
const {ApplicationCommandOptionType} = require('discord.js');

module.exports = {
    name: "poll",
    category: "utils",
    description: "Command to create a poll",
    usage: " poll [your poll]",
    examples: [" poll ZMBOT is fun ?"],
    permissions:["SEND_MESSAGES"],
    ownerOnly: false,

    /* It's option for a slash command. */
    options: [
        {
            name: "title",
            description: "Type the title of your poll",
            type: ApplicationCommandOptionType.String,
            required: true,
        },
        {
            name: "content",
            description: "Type the question of your poll",
            type: ApplicationCommandOptionType.String,
            required: true,
        }
    ],
    /* It's a slash command. */
    async runInteraction(client, interaction) {
        const pollTitle = interaction.options.getString("title");
        const pollContent = interaction.options.getString("content");

        const pollembed = new EmbedBuilder()
        .setTitle(pollTitle)
        .setColor("DARK_BLUE")
        .setDescription(pollContent)
        .setTimestamp()
        .setFooter({text: `New poll generated by ${interaction.user.tag}.`})

        const poll = await interaction.reply({embeds: [pollembed], fetchReply: true})
        poll.react("✅")
        poll.react("❌")

        Logger.command(`/poll command executed on the server ${interaction.guild.name} in the channel ${interaction.channel.name} by member ${interaction.user.username} the ${interaction.createdAt}`)
    }, 
};